---
title: "Zwiller_Lab_3"
author: "Thomas Zwiller"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Library Import
```{r}
library(igraph)
library(ggraph)
library(ggplot2)
library(gplots)
library(ggnetwork)
```

```{r}
nodes <- read.csv('/Users/TomTheIntern/Desktop/Mendoza/Mod 4/Networks/nodelist.csv')
summary(nodes)
edges <- read.csv('/Users/TomTheIntern/Desktop/Mendoza/Mod 4/Networks/edgelist.csv')
summary(edges)
```

```{r}
# make network object####
names(edges)
names(nodes)
# you might need the first column in the datasets to have the same name
net <- igraph::graph_from_data_frame(edges, directed = T, vertices = nodes) # set the network to directed
#graph_from_data_frame is how we turn two separate datasets into a single network in R
net # column for ID is now called "name"

is_simple(net) #does the network have loops or multiplex ties?
is_directed(net) #does the network have directed ties?
```

```{r}
#### Building a visualization####
# some layout options for ggraph: 
# "stress", "star", "circle", "gem", "dh", "graphopt", 
# "grid", "mds", "randomly", "fr", "kk", "drl", "lgl"
```

```{r}
# 0 - default####
ggraph(net, layout = "graphopt") + 
  geom_edge_link() + 
  geom_node_point() +
  ggnetwork::theme_blank() #I like to add this to make the background plain white rather than grey
```

```{r}
# 1 - node labels####
ggraph(net, layout = "graphopt") +
  geom_edge_link() +
  geom_node_point() +
  geom_node_label(aes(label = Name), repel = T, size = 4, color = "black", fill = "white", label.size = 0.1) + #text in a box
  # NOTE: When you create the network object, 
  # repel offsets the text from the node
  # size is the size of the label
  # color is the color of the label, box outline, and line connecting label to node
  # fill is the color of the inside of the box
  # label.size is the thickness of the box outline
  ggnetwork::theme_blank()

ggraph(net, layout = "stress") +
  geom_edge_link() +
  geom_node_point() +
  geom_node_text(aes(label = Name), repel = T, size = 4, color = "#9fab9f") + #plain text
  ggnetwork::theme_blank()
```

```{r}
# 2 - transparency####
ggraph(net, layout = "graphopt") +
  geom_edge_link(alpha = 0.1) + #alpha is opacity (0.1 means 10% opaque)
  geom_node_point() +
  geom_node_label(aes(label = name), repel = T, label.size = 0.1, alpha = 0.1, color = "grey50", fill = "#D7DFD7") +
  ggnetwork::theme_blank()
```

```{r}
# 3 - node shape, size, color####
ggraph(net, layout = "graphopt") + 
  geom_edge_link() + 
  geom_node_point(shape = ifelse(V(net)$Gender == "F", "circle", "square")) + 
  #shapes can also be numeric, as shown in this chart: http://www.sthda.com/english/wiki/ggplot2-point-shapes
  ggnetwork::theme_blank()

ggraph(net, layout = "graphopt") + 
  geom_edge_link() + 
  geom_node_point(size = 6) + #can be numeric, or based on a network variable
  ggnetwork::theme_blank()

table(nodes$Gender)
mycols <- colorpanel(length(unique(nodes$class)), low = "#EFD9D3", high = "#402922")
mycols #I like using this to make sure colors are visually equidistant
ggraph(net, layout = "graphopt") + 
  geom_edge_link() + 
  geom_node_point(color = "black", #color is for the ring around the node
                  fill = ifelse(V(net)$Gender == 'M', "#00008b","#FC6C85"), #fill is the color for the center
                  shape = ifelse(V(net)$Gender == "M", 22, 24))+ #specific shapes needed to have both color and fill (shapes 21-25)
  ggnetwork::theme_blank()
```

```{r}
# 4 - edge direction, thickness, color####
ggraph(net, layout = "graphopt") +
  geom_edge_link(arrow = grid::arrow(angle = 20, #how wide should the arrow be
                                      length = unit(0.10, "in"), #how long should the arrow be
                                      type = "closed")) + #vs open arrow
  geom_node_point() +
  ggnetwork::theme_blank()


ggraph(net, layout = "graphopt") +
  geom_edge_link(aes(width = strength)) + #weight is the name of the variable for tie strength
  scale_edge_width(range = c(0.15, 2)) + #default width is VERY wide, so I recommend reducing
  geom_node_point() +
  ggnetwork::theme_blank() + 
  theme(legend.position = "none") # I don't find the legend necessary in this case

ggraph(net, layout = "graphopt") + 
  geom_edge_link0(edge_color=ifelse(E(net)$type == 'Friend', "#3D3D3D", "#6C79DB")) + #friendly ties are red, others are grey
  #NOTE to get colors to render you must use geom_edge_link0 rather than geom_edge_link
  geom_node_point() +
  ggnetwork::theme_blank()
```

```{r}
# 5 - combination####
ggraph(net, layout = "graphopt") +
  geom_edge_link0(edge_color=ifelse(E(net)$type == 'Friend',"#3D3D3D", "#6C79DB"), 
                  aes(width = strength), alpha = .5, 
                  arrow = grid::arrow(angle = 15,
                                      length = unit(0.12, "in"),
                                      type = "closed")) +
  scale_edge_width(range = c(0.15, 1.5)) +
  geom_node_point(size = 3, 
                  color = "black", 
                  fill = ifelse(V(net)$Gender == 'M', "#00008b","#FC6C85"), 
                  shape = ifelse(V(net)$Gender == "M", 22, 24)) +
  ggnetwork::theme_blank(legend.position = "none") #put it all together!
```


<br>
<br>
<br>
<br>
<br>
<br>
<br>
