---
title: "Homework 3"
author: "Thomas Zwiller"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document: default
---

```{r message=FALSE, warning=FALSE}
#Loading the packages I'll need
library(ggpubr)
library(ggraph)
library(dplyr)
library(igraph) 
library(sna)
library(intergraph) 
library(lme4)
library(lmerTest)
```

```{r}
#Importing the node and edge csv's
nodes <- read.csv('/Users/TomTheIntern/Desktop/Mendoza/Mod 4/Networks/Homework 3/msbr_70340_SP25_sociocentric_nodelist.csv')
summary(nodes)
edges <- read.csv('/Users/TomTheIntern/Desktop/Mendoza/Mod 4/Networks/Homework 3/msbr_70340_SP25_sociocentric_edgelist.csv')
summary(edges)
```

```{r}
# Create igraph and sna object and visualize the network
# first list the edgelist, whether the network is directed, and the vertex attributes.
net <- graph_from_data_frame(edges, directed = T, vertices = nodes)

#making the igraph object into an sna object
net_s <- igraph::simplify(net)
net_s_sna <- asNetwork(net_s) 
```

```{r}
#Test transitivity vs density
Cug_Edges <- sna::cug.test(net_s_sna, gtrans, cmode="edges")

#making the plot
plot(Cug_Edges)

#our network
Cug_Edges$obs.stat 

# simulated networks
summary(Cug_Edges$rep.stat) 
```


```{r}
un_net <- graph_from_data_frame(edges, directed = F, vertices = nodes)

set.seed(1)
clv <- cluster_louvain(un_net, resolution = 3)
modularity(clv) 
communities(clv)
```

```{r}
edges_nodes <- read.csv('/Users/TomTheIntern/Desktop/Mendoza/Mod 4/Networks/Homework 3/egocentric_networks_SP25.csv')

edges_nodes$type <- as.factor(edges_nodes$type)
edges_nodes$ego_gender <- as.factor(edges_nodes$ego_gender)
edges_nodes$alter_gender <- as.factor(edges_nodes$alter_gender)

edges_nodes$ego_age <- as.numeric(edges_nodes$ego_age)
edges_nodes$alter_age <- as.numeric(edges_nodes$alter_age)

model1 <- lmer(strength ~ type + ego_age + alter_age + ego_gender + alter_gender + (1 | ego_id), data = edges_nodes, REML = TRUE, na.action = na.omit)

summary(model1)
```





